@echo off
REM flash-atzgauge.bat -- Flash the AtzGauge voice-slave firmware to COM3
REM
REM Why a .bat and not a one-liner: the flash_args response-file syntax (@flash_args)
REM plus nested PowerShell quoting through tools\idf-run.ps1 is impossible to get
REM reliable on Windows. A batch file with explicit absolute paths has no quoting
REM ambiguity at all. Run it through idf-run.ps1 so the IDF env (esptool) is set up:
REM
REM   powershell -NoProfile -ExecutionPolicy Bypass -File tools\idf-run.ps1 ^
REM       -Command "cmd /c tools\flash-atzgauge.bat"
REM
REM Addresses come from build\flash_args (generated by the build), kept in sync here
REM because they must be passed as separate arguments.
REM
REM NOTE: %~dp0 is this script's own directory, so it works from any cwd.

set BUILD=%~dp0..\xiaozhi-esp32\src\build

python -m esptool --chip esp32s3 --port COM3 --baud 460800 ^
  --before default-reset --after hard-reset ^
  write-flash --flash-mode dio --flash-freq 80m --flash-size 16MB ^
  0x0      "%BUILD%\bootloader\bootloader.bin" ^
  0x8000   "%BUILD%\partition_table\partition-table.bin" ^
  0xd000   "%BUILD%\ota_data_initial.bin" ^
  0x800000 "%BUILD%\generated_assets.bin" ^
  0x20000  "%BUILD%\xiaozhi.bin"

exit /b %ERRORLEVEL%
